name: flutter_best_practice
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # sqlite 存储
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.4
  path_provider: ^2.0.9
  path: ^1.8.0

  # 状态管理
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  # 数据
  freezed_annotation:
  json_annotation:

  # 路由
  auto_route:

  # 网络请求
  dio: ^4.0.4

  # 弹窗
  flutter_easyloading: ^3.0.3

  # rss
  webfeed: ^0.7.0
  google_nav_bar: ^5.0.6

  rflutter_alert: ^2.0.4
  progress_state_button: ^1.0.4
  cached_network_image: ^3.2.0
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.6.0
  line_icons: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_html: ^2.2.1
  url_launcher: ^6.0.18
  photo_view: ^0.13.0
  favicon: ^1.0.15
  logger: ^1.1.0
  group_list_view: ^1.1.1

  flutter_spinkit: ^5.1.0
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  drift_dev: ^1.5.2
  build_runner: ^2.1.5
  freezed:
  auto_route_generator:
  json_serializable:
  flutter_gen_runner:

# 国际化
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true
  assets:
    - assets/images/